name: further-promohub
dependencies:
  - python=3.11.*
  - pip
  - pip:
    - google-api-python-client
    - google-auth-oauthlib 
    - google-auth-httplib2 ==0.2.0
    - google-auth
    - numpy
    - pandas
